"""
Build the data for the static web demo (deployed to Vercel).

A static site can't query DuckDB, so this exports everything the demo needs
as plain JSON into web/data/:

    summary.json          headline numbers, by-type accuracy, confusion matrix
    cases.json            one entry per exception case (facts + proposal + grade)
    traces/CASE-XXX.json  the agent's full reasoning for one case

Unlike everything else under data/, these files ARE committed: Vercel serves
the repo, so the site only works if its data is in git. That's safe — the
data is synthetic, tiny, and regenerated by this script.

The demo is READ-ONLY. It never calls the Claude API, so the published site
costs nothing to run and needs no API key.

Run it:
    python -m recon.pipeline.build_web_demo
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone

import duckdb

from recon.config import settings
from recon.evals.grade import (
    accuracy,
    accuracy_by_type,
    confusion_matrix,
    fully_correct,
    grade_run,
)

WEB_DATA_DIR = settings.project_root / "web" / "data"

# Tool results can be long; the demo shows a readable slice of each.
MAX_RESULT_CHARS = 1500


def json_safe(value):
    """Dates, Decimals and numpy numbers -> plain JSON values."""
    if hasattr(value, "isoformat"):
        return value.isoformat()
    if hasattr(value, "item"):          # numpy scalar
        value = value.item()
    if isinstance(value, float) or value is None or isinstance(value, (int, str, bool)):
        return value
    return float(value) if str(value).replace(".", "").replace("-", "").isdigit() else str(value)


def query(sql: str) -> list[dict]:
    with duckdb.connect(str(settings.duckdb_path), read_only=True) as con:
        cursor = con.execute(sql)
        columns = [col[0] for col in cursor.description]
        return [{col: json_safe(val) for col, val in zip(columns, row)} for row in cursor.fetchall()]


def build_summary(run_id: str, results) -> dict:
    """Headline numbers for the overview and evaluation pages."""
    reconciliation = query("select * from analytics.metrics_reconciliation_summary")[0]
    by_break_type = query("""
        select exception_type, cases, break_value, share_of_value,
               cases_needing_an_entry, agent_cost_usd
        from analytics.metrics_exceptions_by_type order by break_value desc
    """)
    runs = query("select * from analytics.metrics_agent_runs order by started_at")

    matrix = confusion_matrix(results)
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "run_id": run_id,
        "model": runs[-1]["model_requested"] if runs else None,
        "reconciliation": reconciliation,
        "break_types": by_break_type,
        "runs": runs,
        "eval": {
            "cases": len(results),
            "classification_accuracy": float(accuracy(results)),
            "fix_accuracy": float(accuracy(results, "fix_correct")),
            "fully_correct": float(fully_correct(results)),
            "total_cost_usd": float(results["cost_usd"].sum()),
            "cost_per_case_usd": float(results["cost_usd"].mean()),
            "median_seconds": float(results["latency_seconds"].median()),
            "tool_calls": int(results["tool_calls"].sum()),
            "by_type": accuracy_by_type(results).to_dict("records"),
            "confusion": {
                "types": list(matrix.index),
                "predicted": list(matrix.columns),
                "rows": matrix.values.tolist(),
            },
        },
    }


def build_cases(results) -> list[dict]:
    """One entry per case: the facts, the agent's answer, and its grade."""
    grades = {row["case_id"]: row for row in results.to_dict("records")}
    cases = query("select * from analytics.fct_exception_cases order by case_id")
    proposals = {p["case_id"]: p for p in query(
        "select case_id, proposal_id, explanation, evidence, lines_json from staging.stg_agent_proposals "
        "qualify row_number() over (partition by case_id order by created_at desc) = 1")}

    demo_cases = []
    for case in cases:
        proposal = proposals.get(case["case_id"], {})
        grade = grades.get(case["case_id"], {})
        demo_cases.append({
            **case,
            "explanation": proposal.get("explanation"),
            "evidence": proposal.get("evidence"),
            "lines": json.loads(proposal["lines_json"]) if proposal.get("lines_json") else [],
            "expected_type": grade.get("expected_type"),
            "classification_correct": bool(grade.get("classification_correct", False)),
            "fix_correct": bool(grade.get("fix_correct", False)),
            "expected_cash_adjustment": grade.get("expected_cash_adjustment"),
            "proposed_cash_effect": grade.get("proposed_cash_effect"),
        })
    return demo_cases


def build_trace(trace: dict) -> dict:
    """A trimmed trace: enough to follow the reasoning, small enough to serve."""
    return {
        "case_id": trace["case_id"],
        "status": trace["status"],
        "latency_seconds": trace["latency_seconds"],
        "totals": trace["totals"],
        "final_summary": trace["final_summary"],
        "steps": [{
            "step": step["step"],
            "stop_reason": step["stop_reason"],
            "model_seconds": step["model_seconds"],
            "cost_usd": step["cost_usd"],
            "thinking": step["thinking"],
            "text": step["text"],
            "tool_calls": step["tool_calls"],
            "tool_results": [{
                "is_error": result["is_error"],
                "text": result["text"][:MAX_RESULT_CHARS],
                "truncated": len(result["text"]) > MAX_RESULT_CHARS,
            } for result in step["tool_results"]],
        } for step in trace["steps"]],
    }


def build(run_id: str | None = None) -> dict[str, int]:
    """Write every demo file. Returns {what: count}."""
    run_id, results = grade_run(run_id)

    # Start clean, so a case removed upstream can't linger in the demo.
    if WEB_DATA_DIR.exists():
        shutil.rmtree(WEB_DATA_DIR)
    (WEB_DATA_DIR / "traces").mkdir(parents=True)

    (WEB_DATA_DIR / "summary.json").write_text(json.dumps(build_summary(run_id, results), indent=2))
    cases = build_cases(results)
    (WEB_DATA_DIR / "cases.json").write_text(json.dumps(cases, indent=2))

    traces = 0
    for path in sorted((settings.traces_dir / run_id).glob("CASE-*.json")):
        trace = json.loads(path.read_text())
        (WEB_DATA_DIR / "traces" / f"{trace['case_id']}.json").write_text(
            json.dumps(build_trace(trace), indent=2))
        traces += 1

    return {"cases": len(cases), "traces": traces}


def main() -> None:
    counts = build()
    size_kb = sum(f.stat().st_size for f in WEB_DATA_DIR.rglob("*")) / 1024
    print(f"Built the web demo data in {WEB_DATA_DIR.relative_to(settings.project_root)}/")
    print(f"  {counts['cases']} cases, {counts['traces']} traces, {size_kb:.0f} KB total")
    print("These files ARE committed — Vercel serves them as the demo's data.")


if __name__ == "__main__":
    main()
