"""
Export the analytics tables for Power BI — Phase 9, Step 5.

Writes each analytics table to data/processed/analytics/ as BOTH:
    .parquet  - typed and compact; Power BI reads it natively
    .csv      - readable by anything, and easy to eyeball

The numbers are computed in dbt, never in the BI tool. The dashboard
displays them; it does not define them. That is what stops two dashboards
disagreeing about what "match rate" means.

Run it (after dbt has built the analytics models):
    python -m recon.pipeline.export_analytics
"""

from __future__ import annotations

import duckdb

from recon.config import settings

# The tables a dashboard binds to. Explicit list, so nothing unexpected
# (e.g. a scratch table) gets published by accident.
ANALYTICS_TABLES = [
    "fct_exception_cases",
    "metrics_reconciliation_summary",
    "metrics_exceptions_by_type",
    "metrics_resolution_status",
    "metrics_agent_runs",
]

README = """\
# Analytics exports (Power BI)

Generated by `python -m recon.pipeline.export_analytics`. Do not edit by hand:
every file is overwritten on each export.

| File | One row per | Use |
|---|---|---|
| `fct_exception_cases` | exception case | The fact table — build anything from this |
| `metrics_reconciliation_summary` | statement month | Match rate (count and value), open break value, resolution rate |
| `metrics_exceptions_by_type` | exception type | What kinds of breaks, what they're worth, agent cost |
| `metrics_resolution_status` | review status | The review queue: pending / approved / rejected |
| `metrics_agent_runs` | agent run | Cost, latency and completion rate per run |

## Connecting Power BI

1. **Get data → Folder**, and choose this folder (recommended: load the
   `.parquet` files, which keep their data types).
2. Or **Get data → Text/CSV** for a single table.
3. Relationships: join every metrics table to `fct_exception_cases` on the
   column they share (`exception_type` -> `classification`,
   `review_status`, `run_id`).

Accuracy against ground truth is NOT here: it lives in
`data/eval/reports/<run_id>/results.csv`. Ground truth only exists because
this is a synthetic demo, so it is kept out of the operational warehouse.
"""


def export_all() -> dict[str, int]:
    """Write every analytics table as Parquet + CSV. Returns {table: rows}."""
    folder = settings.processed_dir / "analytics"
    folder.mkdir(parents=True, exist_ok=True)

    counts = {}
    with duckdb.connect(str(settings.duckdb_path), read_only=True) as con:
        for table in ANALYTICS_TABLES:
            source = f"analytics.{table}"
            # COPY ... TO writes the query result straight to a file.
            con.execute(f"COPY (SELECT * FROM {source}) TO '{folder / f'{table}.parquet'}' (FORMAT PARQUET)")
            con.execute(f"COPY (SELECT * FROM {source}) TO '{folder / f'{table}.csv'}' (FORMAT CSV, HEADER)")
            counts[table] = con.execute(f"SELECT count(*) FROM {source}").fetchone()[0]

    (folder / "README.md").write_text(README)
    return counts


def main() -> None:
    counts = export_all()
    folder = (settings.processed_dir / "analytics").relative_to(settings.project_root)
    print(f"Exported to {folder}/ (.parquet + .csv):")
    for table, rows in counts.items():
        print(f"  {table:<32} {rows:>4} rows")
    print(f"\nPower BI: Get data -> Folder -> {folder} (see its README.md)")


if __name__ == "__main__":
    main()
